a=int(input("Enter value of a: "))
b=int(input("Enter value of b: "))
print("Addition: ",a+b)
print("Subtraction: ",a-b)
print("Multiplication: ",a*b)
print("Division: ",a/b)
print("FloorDivision: ",a//b)
print("Modulus: ",a%b)
print("Exponential: ",a**b)
